### ISSUE TITLE
Error when calling 'qmake' (cannot find file 'qss/port.qss')

### ISSUE THREAD

**Issue by lukassnoek** [TimVanMourik/Porcupine#6]
When calling qmake (on Ubuntu 16.04), I got the error:
RCC: Error in 'resources/resources.qrc': Cannot find file 'qss/port.qss'

When copying Resources/qss/port.qss to resources/qss, it _does_ work (but I'm not sure whether it breaks anything elsewhere in the package).

**Comment by TimVanMourik** [comment]
Hmm, that's weird. I have indeed been working on the qss files, but don't believe I deleted this one and for me it's still working. I think I fixed it and for Windows it's definitely owkring now. Could you please try it again?

**Comment by lukassnoek** [comment]
Nope, still the same error. 
In resources/resources.qrc there is a reference to qss/port.qss:
`<file alias="port.qss">qss/port.qss</file>`

But this file only exists in Resources/qss/port.qss ... (This is also the case in the Github repo)

**Comment by TimVanMourik** [comment]
Aaahhh, got it. Of course. Windows is case insensitive, so to me, it showed the files in the same directory all along. It should indeed all be in lower case resources, and it's fixed now!
